
- hosts: all
  remote_user: ubuntu
  pre_tasks:
  - name: update system
    apt:
      update_cache: yes
      upgrade: safe
      autoclean: yes
      autoremove: yes
    become: yes

  tasks:
    - include: tasks/containerd.yml
    - include: tasks/cron.yml