
- hosts: all
  remote_user: ubuntu
  tasks:
  - name: update system
    apt:
      update_cache: yes
      upgrade: safe
      autoclean: yes
      autoremove: yes
    become: yes

- name: docker install
  hosts: all
  remote_user: ubuntu
  roles:
  - apt-over-https
  - docker
