- name: install cron job (ansible-pull)
  cron: 
    user: ansible
    name: run ansible configuration
    job: /usr/bin/ansible-pull -o -U git@github.com:exploding-pear/homelab-iac.git > /dev/null
    minute: "*/10"