- name: ensure that br_netfilter module is loaded
  modprobe:
    name: br_netfilter
    state: present

- name: ensure that overlay module is loaded
  modprobe:
    name: overlay
    state: present

- name: ensure that swap is disabled
  shell: swapoff -a

- name: ensure apt-transport-https is installed
  apt:
    name: apt-transport-https
    state: present

- name: ensure ca-certificates is installed
  apt:
    name: ca-certificates
    state: present
    
- name: ensure curl is installed
  apt:
    name: curl
    state: present

- name: ensure ansible.posix is installed
  shell: ansible-galaxy collection install ansible.posix
    
- name: ensure software-properties-common is installed
  apt:
    name: software-properties-common
    state: present

- name: ensure docker gpg key is on system
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: ensure docker repo is on system
  apt_repository:
    repo: deb [arch=arm64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    update_cache: yes

- name: copy overlay.conf into /etc/modules-load.d
  copy:
    src: files/containerd.conf
    dest: /etc/modules-load.d
    owner: root
    group: root
    mode: '0644'

- ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    sysctl_set: yes
    state: present
    reload: yes

- ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    sysctl_set: yes
    state: present
    reload: yes

- ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    sysctl_set: yes
    state: present
    reload: yes

- name: ensure latest version of containerd.io installed
  apt:
    name: containerd.io
    state: latest

- name: store containerd default config in 
  shell:
    cmd: containerd config default > /etc/containerd/config.toml
    chdir: /etc/containerd/
    creates: /etc/containerd/config.toml

- name: restart containerd
  systemd:
    name: containerd
    state: restarted
    enabled: yes

- name: ensure that google cloud gpg key is on system
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: ensure kubernetes repo is on system
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    update_cache: yes

- name: ensure kubelet is installed
  apt:
    name: kubelet
    state: present

- name: prevent kubelet from being upgraded
  dpkg_selections:
    name: kubelet
    selection: hold

- name: ensure kubeadm is installed
  apt:
    name: kubeadm
    state: present

- name: prevent kubeadm from being upgraded
  dpkg_selections:
    name: kubeadm
    selection: hold

- name: ensure kubectl is installed
  apt:
    name: kubectl
    state: present

- name: prevent kubectl from being upgraded
  dpkg_selections:
    name: kubectl
    selection: hold

- name: Check that the control-plane file exists
  stat:
    path: /home/ubuntu/control-plane
  register: controlplane