- name: docker absent
  apt:
    name: docker
    state: absent

- name: docker engine absent
  apt:
    name: docker-engine
    state: absent

- name: docker.io absent
  apt:
    name: docker.io
    state: absent

- name: containerd absent
  apt:
    name: containerd
    state: absent
    
- name: runc absent
  apt:
    name: runc
    state: absent

- name: ensure docker gpg key is on system
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: ensure docker repo is on system
  apt_repository:
    repo: deb [arch=arm64] https://download.docker.com/linux/ubuntu focal stable
    state: present
  become: true

- name: ensure latest version of docker-ce installed
  apt:
    name: docker-ce
    state: latest
  become: true
  
- name: ensure latest version of docker-ce-cli installed
  apt:
    name: docker-ce-cli
    state: latest
  become: true

- name: ensure latest version of containerd.io installed
  apt:
    name: containerd.io
    state: latest
  become: true

- name: ensure docker group exists
  group:
    name: docker
    state: present
  
- name: ensure user is part of the docker group
  user:
    name: ubuntu
    group: docker
    append: yes
  become: true

- name: ensure docker is started, and starts on system reboots
  systemd:
    name: docker
    state: started
    enabled: yes
  become: true